name: Comment on an issue
on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Console log step
        uses: actions/github-script@v7
        with:
          script: console.log(context)
      
        
      - name: Create comment step
        uses: actions/github-script
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
        