name: Validate input type
on:
  workflow_dispatch:
    inputs:
      fixVersion:
        description: "Enter fix version ID when running test pack 'ALL QA sites smoke tests'. Found in the JIra release URL i.e. /UNBO/versions/18061/"
        required: true
  # push:
  #   branches:
  #     - master

jobs:
  validate-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs validation check
        run: |
          if [[ ! ${{ github.event.inputs.fixVersion }} =~ ^[0-9]+$ ]]; then
            echo "Fix version must be an integer."
            exit 1
          fi

      # - name: Inputs validation check
      #   run: |
      #     if [[ ! $${{ github.event.inputs.fixVersion }} =~ ^[0-9]+$ ]]; then
      #       echo "Fix version must be an integer."
      #       exit 1
      #     fi
    
