name: Validate input type
on:
  workflow_dispatch:
    inputs:
      fixVersion:
        description: "Enter fix version ID when running test pack 'ALL QA sites smoke tests'. Found in the JIra release URL i.e. /UNBO/versions/18061/"
        required: true
  # push:
  #   branches:
  #     - master

jobs:
  validate-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs validation check
        uses: actions/github-script@v7
        with:
          script: |
            const fixVersionInput = github.event.inputs.fixVersion;
            console.log(fixVersionInput)

            # // Check if fixVersionInput is not empty
            # if (!fixVersionInput) {
            #   core.setFailed('Enter a fix version when running QA smoke tests!');
            # } else {
            #   // Try parsing the input as an integer
            #   const fixVersion = parseInt(fixVersionInput);

            #   // Check if the parsing was successful and fixVersion is an integer
            #   if (isNaN(fixVersion)) {
            #     core.setFailed('Fix version must be an integer!');
            #   }
            # }
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          # debug: false
